# Generated by Django 5.0.4 on 2024-07-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_product_gender_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('children', 'CHILDREN')], max_length=10, null=True),
        ),
    ]
