# Generated by Django 5.0.4 on 2024-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('children', 'CHILDREN'), ('female', 'FEMALE'), ('male', 'MALE')], max_length=10, null=True),
        ),
    ]
