# Generated by Django 5.0.4 on 2024-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_gender_alter_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Children', 'Children'), ('Men', 'Men'), ('Women', 'Women')], max_length=10, null=True),
        ),
    ]
