# Generated by Django 3.2.25 on 2024-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_gender_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('Women', 'Women'), ('Children', 'Children'), ('Men', 'Men')], max_length=10, null=True),
        ),
    ]
