# Generated by Django 3.2.25 on 2024-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('Children', 'Children'), ('Women', 'Women'), ('Men', 'Men')], max_length=10, null=True),
        ),
    ]
