# Generated by Django 5.0.4 on 2024-07-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
