# Generated by Django 5.0.4 on 2024-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('vendor', 'Vendor')], default='client', max_length=10, null=True),
        ),
    ]
